# Generated by Django 5.0.3 on 2024-04-21 06:46

import product.helpes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fruit', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to=product.helpes.SaveImages.product_images_path)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price_type', models.CharField(choices=[('$', 'USD'), ('sum', 'UZS')], default='$', max_length=10)),
                ('category', models.CharField(choices=[('vegetables', 'vegetables'), ('fruit', 'fruit'), ('bread', 'bread'), ('meat', 'meat')], default='fruit', max_length=20)),
                ('discount', models.CharField(choices=[('0', '0%'), ('10', '10%'), ('20', '20%'), ('30', '30%'), ('40', '40%'), ('50', '50%'), ('60', '60%'), ('70', '70%'), ('80', '80%'), ('90', '90%'), ('100', '100%')], default='0')),
                ('quality', models.CharField(choices=[('organic', 'organic'), ('fresh', 'fresh'), ('discount', 'discount'), ('expired', 'expired')], default='organic', max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
