# Generated by Django 5.0.3 on 2024-04-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='slug',
        ),
    ]
